
import java.sql.*;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sakib
 */
public class frameStaffProfilePage extends javax.swing.JFrame {

    public int staffId;

    /**
     * Creates new form frameStaffProfilePage
     */
    public frameStaffProfilePage() {
        initComponents();
        setSize(1000, 800);
    }

    public void setComponentStaffProfilePage(int id) {
        staffId = id;
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=RainbowPrimarySchool;selectMethod=cursor", "sa", "123456");

            // find if the username and password exist in database and also get the student id
            String sqlQuery = "select staffFirstName, staffLastName, staffDOB,staffBG,staffPhone,staffEmail,staffNID,staffAccountNo,staffAddress from StaffTable where staffId = ?;";

            PreparedStatement statement = connection.prepareStatement(sqlQuery);

            statement.setInt(1, id);

            String FirstName = null;
            String Lastname = null;
            
            String dateofBitrh = null;
            String nid = null;
            String phone = null;
            String email = null;
            String bloodGroup = null;
            
            String accNo = null;
            String address = null;
            

            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                // Retrieve data for each row
                FirstName = resultSet.getString("staffFirstName");
                Lastname = resultSet.getString("staffLastName");
                
                dateofBitrh = resultSet.getString("staffDOB");
                bloodGroup = resultSet.getString("staffBG");
                phone = resultSet.getString("staffPhone");
                email = resultSet.getString("staffEmail");
                nid= resultSet.getString("staffNID");
                accNo = resultSet.getString("staffAccountNo");
                address = resultSet.getString("staffAddress");
            }
            lblHead.setText(FirstName+" Profile");
            lblFirstname.setText(FirstName);
            lblLastName.setText(Lastname);
            lblDateofBirth.setText(dateofBitrh);
            lblBlood.setText(bloodGroup);
            tfPhone.setText(phone);
            tfEmail.setText(email);
            tfAddress.setText(address);
            lblAccount.setText(accNo);
            

            //System.out.println(StudentClassId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        lblDateofBirth = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        btnSaveChanges = new javax.swing.JButton();
        lblBlood = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        tfPhone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNid.setForeground(new java.awt.Color(255, 255, 255));
        lblNid.setText("jLabel16");
        getContentPane().add(lblNid, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 242, 250, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 148, 150, 40));

        btnHome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 38, 101, 51));

        lblDateofBirth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDateofBirth.setForeground(new java.awt.Color(255, 255, 255));
        lblDateofBirth.setText("jLabel12");
        getContentPane().add(lblDateofBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 242, 250, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NID:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 241, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date of Birth:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 241, 150, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 332, 150, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone No:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 332, 150, 40));

        lblAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 411, 250, 40));

        btnSaveChanges.setBackground(new java.awt.Color(51, 204, 0));
        btnSaveChanges.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 690, 242, 54));

        lblBlood.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlood.setForeground(new java.awt.Color(255, 255, 255));
        lblBlood.setText("jLabel18");
        getContentPane().add(lblBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 405, 250, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood Group:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 404, 150, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 498, 150, 40));

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("jLabel15");
        getContentPane().add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 149, 250, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Account No:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 411, 150, 40));

        lblHead.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        lblHead.setForeground(new java.awt.Color(255, 255, 255));
        lblHead.setText("staff profile");
        getContentPane().add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 25, 492, 79));

        tfAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });
        getContentPane().add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 498, 323, 159));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 148, 150, 40));

        lblFirstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 148, 250, 40));

        tfPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPhone.setText("jTextField2");
        getContentPane().add(tfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 333, 250, 40));

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfEmail.setText("jTextField3");
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 333, 250, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComnmonBG.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        frameStaffHomePage staffHomePage = new frameStaffHomePage();
        staffHomePage.setComponentsStaffHomePage(staffId);
        staffHomePage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        // TODO add your handling code here:
        
        String phone = tfPhone.getText();
        String email = tfEmail.getText();
        String address = tfAddress.getText();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=RainbowPrimarySchool;selectMethod=cursor", "sa", "123456");

            // find if the username and password exist in database and also get the student id
            String sqlQuery = "UPDATE StaffTable SET staffPhone = ?, staffEmail = ?,staffAddress=?  WHERE staffId = ?";
            
            PreparedStatement statement  = connection.prepareStatement(sqlQuery);

            statement.setString(1, phone);
            statement.setString(2, email);
            statement.setString(3, address);
            statement.setInt(4, staffId);
            int updated = statement.executeUpdate();
            if (updated > 0) {
                JOptionPane.showMessageDialog(frameStaffProfilePage.this, "Update Successful");
            } else {
                JOptionPane.showMessageDialog(frameStaffProfilePage.this, "Update not Successful");
            }
            
           
           //System.out.println(StudentClassId);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameStaffProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameStaffProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameStaffProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameStaffProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameStaffProfilePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBlood;
    private javax.swing.JLabel lblDateofBirth;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNid;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfPhone;
    // End of variables declaration//GEN-END:variables
}
