
import java.sql.*;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sakib
 */
public class frameStudentProfilePage extends javax.swing.JFrame {

    public int studentId;

    /**
     * Creates new form frameStudentProfile
     */
    public frameStudentProfilePage() {
        initComponents();
        setSize(1000, 800);
    }

    public void setComponentsStudentProfilePage(int id) {
        System.out.println(id);
        studentId = id;

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=RainbowPrimarySchool;selectMethod=cursor", "sa", "123456");

            // find if the username and password exist in database and also get the student id
            String sqlQuery = "select studentFirstName, studentLastName, studentFatherName,studentMotherName,studentDOB,studentBG,studentParentPhone,studentEmail,studentAddress,studentAccountNo from StudentTable where studentId = ?;";

            PreparedStatement statement = connection.prepareStatement(sqlQuery);

            statement.setInt(1, id);

            String FirstName = null;
            String Lastname = null;
            String fathersname = null;
            String mothersname = null;
            String dateofBitrh = null;
            String bloodGroup = null;
            String phone = null;
            String email = null;
            String accNo = null;
            String address = null;
            

            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                // Retrieve data for each row
                FirstName = resultSet.getString("studentFirstName");
                Lastname = resultSet.getString("studentLastName");
                fathersname = resultSet.getString("studentFatherName");
                mothersname = resultSet.getString("studentMotherName");
                dateofBitrh = resultSet.getString("studentDOB");
                bloodGroup = resultSet.getString("studentBG");
                phone = resultSet.getString("studentParentPhone");
                email = resultSet.getString("studentEmail");
                accNo = resultSet.getString("studentAccountNo");
                address = resultSet.getString("studentAddress");
                

            }

            lblStudentProfileHead.setText(FirstName + " Profile");
            lblFirstName.setText(FirstName);
            lblLastname.setText(Lastname);
            lblfathersname.setText(fathersname);
            lblmothersname.setText(mothersname);
            lblDateofBirth.setText(dateofBitrh);
            lblBlood.setText(bloodGroup);
            tfPhoneNumber.setText(phone);
            tfEmail.setText(email);
            tfAddress.setText(address);
            lblAccountNo.setText(accNo);

            //System.out.println(StudentClassId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentProfileHead = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblfathersname = new javax.swing.JLabel();
        lblDateofBirth = new javax.swing.JLabel();
        lblAccountNo = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        lblmothersname = new javax.swing.JLabel();
        lblBlood = new javax.swing.JLabel();
        tfPhoneNumber = new javax.swing.JTextField();
        btnSaveChanges = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentProfileHead.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        lblStudentProfileHead.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentProfileHead.setText("student profile");
        getContentPane().add(lblStudentProfileHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 25, 492, 79));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 38, 101, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 148, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Father's Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 207, 150, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date of Birth: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 273, 150, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood Group:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 273, 150, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 148, 150, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mother's Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 207, 150, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone No:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 332, 150, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 499, 150, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Account No:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 411, 150, 40));

        tfAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });
        getContentPane().add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 499, 323, 159));

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 148, 250, 40));

        lblfathersname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblfathersname.setForeground(new java.awt.Color(255, 255, 255));
        lblfathersname.setText("jLabel12");
        getContentPane().add(lblfathersname, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 208, 250, 40));

        lblDateofBirth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDateofBirth.setForeground(new java.awt.Color(255, 255, 255));
        lblDateofBirth.setText("jLabel13");
        getContentPane().add(lblDateofBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 274, 250, 40));

        lblAccountNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAccountNo.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountNo.setText("jLabel14");
        getContentPane().add(lblAccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 412, 565, 40));

        lblLastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("jLabel15");
        getContentPane().add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 149, 250, 40));
        lblLastname.getAccessibleContext().setAccessibleDescription("");

        lblmothersname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblmothersname.setForeground(new java.awt.Color(255, 255, 255));
        lblmothersname.setText("jLabel16");
        getContentPane().add(lblmothersname, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 208, 250, 40));
        lblmothersname.getAccessibleContext().setAccessibleDescription("");

        lblBlood.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlood.setForeground(new java.awt.Color(255, 255, 255));
        lblBlood.setText("jLabel18");
        getContentPane().add(lblBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 274, 250, 40));
        lblBlood.getAccessibleContext().setAccessibleDescription("");

        tfPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPhoneNumber.setText("jTextField2");
        getContentPane().add(tfPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 333, 250, 40));
        tfPhoneNumber.getAccessibleContext().setAccessibleDescription("");

        btnSaveChanges.setBackground(new java.awt.Color(0, 204, 0));
        btnSaveChanges.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 694, 242, 54));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 332, 150, 40));

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfEmail.setText("jTextField1");
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 333, 250, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComnmonBG.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frameStudentHomePage studentHomePage = new frameStudentHomePage();
        studentHomePage.SetComponentsStudentHomePage(studentId);
        studentHomePage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        // TODO add your handling code here:
        String phone = tfPhoneNumber.getText();
        String email = tfEmail.getText();
        String address = tfAddress.getText();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=RainbowPrimarySchool;selectMethod=cursor", "sa", "123456");

            // find if the username and password exist in database and also get the student id
            String sqlQuery = "UPDATE StudentTable SET studentParentPhone = ?, studentEmail = ?,studentAddress=?  WHERE studentId = ?";
            
            PreparedStatement statement  = connection.prepareStatement(sqlQuery);

            statement.setString(1, phone);
            statement.setString(2, email);
            statement.setString(3, address);
            statement.setInt(4, studentId);
            int updated = statement.executeUpdate();
            if (updated > 0) {
                JOptionPane.showMessageDialog(frameStudentProfilePage.this, "Update Successful");
            } else {
                JOptionPane.showMessageDialog(frameStudentProfilePage.this, "Update not Successful");
            }
            
           
           //System.out.println(StudentClassId);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameStudentProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameStudentProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameStudentProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameStudentProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameStudentProfilePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAccountNo;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBlood;
    private javax.swing.JLabel lblDateofBirth;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblStudentProfileHead;
    private javax.swing.JLabel lblfathersname;
    private javax.swing.JLabel lblmothersname;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
