
import java.sql.*;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sakib
 */
public class frameADMINHomePage extends javax.swing.JFrame {

    /**
     * Creates new form frameADMINHomePage
     */
    public frameADMINHomePage() {
        initComponents();
        setSize(1000, 800);
        /// count how many students are there 
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=RainbowPrimarySchool;selectMethod=cursor", "sa", "123456");
            
            // find if the username and password exist in database and also get the student id
            String sqlQuery = "SELECT COUNT(*) AS row_count FROM StudentTable";

            try (Statement statement = connection.createStatement()) {
                // Execute the SELECT COUNT(*) query and get the result set
                ResultSet resultSet = statement.executeQuery(sqlQuery);
                
                // Process the result set and retrieve the count value
                if (resultSet.next()) {
                    int rowCount = resultSet.getInt("row_count");
                    lblTotalStudent.setText(String.valueOf(rowCount));
                    //System.out.println("Number of rows in the table: " + rowCount);
                }                 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // count how many teacher are there 
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=RainbowPrimarySchool;selectMethod=cursor", "sa", "123456");
            
            // find if the username and password exist in database and also get the student id
            String sqlQuery = "SELECT COUNT(*) AS row_count FROM TeacherTable";

            try (Statement statement = connection.createStatement()) {
                // Execute the SELECT COUNT(*) query and get the result set
                ResultSet resultSet = statement.executeQuery(sqlQuery);
                
                // Process the result set and retrieve the count value
                if (resultSet.next()) {
                    int rowCount = resultSet.getInt("row_count");
                    lblTotalTeacher.setText(String.valueOf(rowCount));
                    //System.out.println("Number of rows in the table: " + rowCount);
                }                 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        /// count how many staff are there 
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=RainbowPrimarySchool;selectMethod=cursor", "sa", "123456");
            
            // find if the username and password exist in database and also get the student id
            String sqlQuery = "SELECT COUNT(*) AS row_count FROM StaffTable";

            try (Statement statement = connection.createStatement()) {
                // Execute the SELECT COUNT(*) query and get the result set
                ResultSet resultSet = statement.executeQuery(sqlQuery);
                
                // Process the result set and retrieve the count value
                if (resultSet.next()) {
                    int rowCount = resultSet.getInt("row_count");
                    lblTotalStaff.setText(String.valueOf(rowCount));
                    //System.out.println("Number of rows in the table: " + rowCount);
                }                 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddStudent = new javax.swing.JButton();
        btnAddTeacher = new javax.swing.JButton();
        btnAddStaff = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalStudent = new javax.swing.JLabel();
        lblTotalTeacher = new javax.swing.JLabel();
        lblTotalStaff = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 408, 175, 40));

        btnAddTeacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddTeacher.setText("Add Teacher");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 408, 175, 40));

        btnAddStaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 408, 175, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome Admin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 13, 252, 58));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 37, 99, 47));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Manage Students");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 159, 200, 50));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Manage Teachers");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 159, 200, 50));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Manage Staffs");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 159, 200, 50));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Results");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 150, 50));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("Payment");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 260, 150, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Overview:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 501, 248, 67));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quick Action");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 333, 248, 67));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Students");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 599, 200, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Teachers");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 599, 200, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Staffs");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 599, 200, 80));

        lblTotalStudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalStudent.setForeground(new java.awt.Color(204, 255, 255));
        lblTotalStudent.setText("800");
        getContentPane().add(lblTotalStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 686, 200, 50));

        lblTotalTeacher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalTeacher.setForeground(new java.awt.Color(204, 255, 255));
        lblTotalTeacher.setText("25");
        getContentPane().add(lblTotalTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 686, 200, 50));

        lblTotalStaff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalStaff.setForeground(new java.awt.Color(204, 255, 255));
        lblTotalStaff.setText("30");
        getContentPane().add(lblTotalStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 686, 200, 50));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("Courses");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 260, 150, 50));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComnmonBG.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // TODO add your handling code here:
        frameSignUpAsStudentbyADMIN addStudentbyADMIN2 = new frameSignUpAsStudentbyADMIN();
        addStudentbyADMIN2.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        // TODO add your handling code here:
        frameSignUpAsStaffbyADMIN addStaffbyADMIN = new frameSignUpAsStaffbyADMIN();
        addStaffbyADMIN.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        // TODO add your handling code here:
        frameSignUpAsTeacherbyADMIN addTeacherbyADMIN = new frameSignUpAsTeacherbyADMIN();
        addTeacherbyADMIN.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        int dialogResult = JOptionPane.showConfirmDialog(frame,
                "Do you want to log out from your account?", "Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            frameLogInPage logInPage = new frameLogInPage();
            logInPage.setVisible(true);
            setVisible(false);
        } else {
            // User clicked "No," handle it as needed
            // JOptionPane.showMessageDialog(frame, "You clicked NO. Staying on the current page.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frameManageStudentbyADMIN manageStudentbyADMIN = new frameManageStudentbyADMIN();
        manageStudentbyADMIN.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        frameManageStaffbyADMIN manageStaffbyADMIN = new frameManageStaffbyADMIN();
        manageStaffbyADMIN.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        frameManageTeacherbyADMIN manageTeacherbyADMIN = new frameManageTeacherbyADMIN();
        manageTeacherbyADMIN.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        frameSeeResultbyADMINandTeacher seeResultbyADMIN = new frameSeeResultbyADMINandTeacher();
        seeResultbyADMIN.setComponentsSeeResultbyAdmin("admin", 0);
        seeResultbyADMIN.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        frameManagePaymentbyADMIN managePaymentbyADMIN = new frameManagePaymentbyADMIN();
        managePaymentbyADMIN.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        frameManageCoursesbyADMIN manageCoursesbyADMIN = new frameManageCoursesbyADMIN();
        manageCoursesbyADMIN.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameADMINHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameADMINHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameADMINHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameADMINHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameADMINHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTotalStaff;
    private javax.swing.JLabel lblTotalStudent;
    private javax.swing.JLabel lblTotalTeacher;
    // End of variables declaration//GEN-END:variables
}
