/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sakib
 */
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.JOptionPane;

public class frameSignUpAsStudentbyADMIN extends javax.swing.JFrame {

    /**
     * Creates new form frameSignUpAsStudentbyADMIN2
     */
    public frameSignUpAsStudentbyADMIN() {
        initComponents();
        setSize(1000, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfBlood = new javax.swing.JTextField();
        tfCurrentClass = new javax.swing.JTextField();
        tfCurrentSection = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        comboIsCurrentStudent = new javax.swing.JComboBox<>();
        BtnSubmit = new javax.swing.JButton();
        dateBirthday = new com.toedter.calendar.JDateChooser();
        dateDateOfAdmission = new com.toedter.calendar.JDateChooser();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfFirstname = new javax.swing.JTextField();
        tfLastname = new javax.swing.JTextField();
        tfFathersname = new javax.swing.JTextField();
        tfMothersName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfPhone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfAccountNo = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 122, 160, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 122, 160, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Father's Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 195, 160, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mother's Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 195, 160, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Birthday:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 270, 160, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Blood Group:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 270, 160, 40));

        tfBlood.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 200, 40));

        tfCurrentClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfCurrentClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 468, 200, 40));

        tfCurrentSection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfCurrentSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 468, 200, 40));

        tfUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 599, 200, 40));

        tfPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 599, 200, 40));

        comboIsCurrentStudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboIsCurrentStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        getContentPane().add(comboIsCurrentStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 691, 120, -1));

        BtnSubmit.setBackground(new java.awt.Color(51, 204, 0));
        BtnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnSubmit.setText("SUBMIT");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 675, 160, 50));
        getContentPane().add(dateBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 270, 200, 40));
        getContentPane().add(dateDateOfAdmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 541, 200, 40));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 679, 108, 42));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Current Class:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 468, 160, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Current Section:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 468, 160, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date of Admission: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 541, 160, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Username:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 599, 160, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 599, 160, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("IS CURRENT STUDENT:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 688, 300, 30));

        tfFirstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 122, 200, 40));

        tfLastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLastnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 122, 200, 40));

        tfFathersname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfFathersname, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 195, 200, 40));

        tfMothersName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfMothersName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 195, 200, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Sign Up By ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 34, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Phone Number:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 341, 160, 40));

        tfPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(tfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 341, 200, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 341, 160, 40));

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 341, 200, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 399, 160, 40));

        tfAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });
        getContentPane().add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 399, 200, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Account NO:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 399, 160, 40));

        tfAccountNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tfAccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 399, 200, 40));

        lblBackground.setForeground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComnmonBG.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        // TODO add your handling code here:
        if (tfFirstname.getText().trim() == null || tfLastname.getText().trim() == null
                || tfFathersname.getText().trim() == null || tfMothersName.getText().trim() == null
                || dateBirthday.getDate() == null || tfPhone.getText().trim() == null
                || tfEmail.getText().trim() == null || tfAccountNo.getText().trim() == null
                || tfCurrentClass.getText().trim() == null || tfCurrentClass.getText().trim() == null
                || dateDateOfAdmission.getDate() == null || tfUsername.getText().trim() == null
                || tfPassword.getText().trim() == null) {
            JOptionPane.showMessageDialog(frameSignUpAsStudentbyADMIN.this, " please enter all the information");
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager
                        .getConnection(
                                "jdbc:sqlserver://localhost:1433;databaseName=RainbowPrimarySchool;selectMethod=cursor", "sa", "123456");

                System.out.println("DATABASE NAME IS:"
                        + connection.getMetaData().getDatabaseProductName());

                PreparedStatement ps = connection.prepareStatement("insert into StudentTable (studentFirstName,studentLastName,studentFatherName,studentMotherName,studentDOB,studentBG,studentParentPhone,studentEmail,studentAddress,studentAccountNo,studentCurentClass,studentSection,studentAdmissionDate,studentUsername,studentPassword,isCurrentStudent) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

                //ps.setInt(1, Integer.parseInt(tfStudentId_signStdbyADM.getText()));// student id
                ps.setString(1, tfFirstname.getText());// first namer
                ps.setString(2, tfLastname.getText());// last name
                ps.setString(3, tfFathersname.getText());
                ps.setString(4, tfMothersName.getText());
                SimpleDateFormat dtformat = new SimpleDateFormat("yyyy-MM-dd");
                String bddate = dtformat.format(dateBirthday.getDate());
                ps.setString(5, bddate); // birthday 
                ps.setString(6, tfBlood.getText());
                //ps.setInt(7,Integer.parseInt(tfCurrentClass.getText()));
                ps.setString(7, tfPhone.getText());
                ps.setString(8, tfEmail.getText());
                ps.setString(9, tfAddress.getText());
                //ps.setString(9,dtformat.format(dateDateOfAdmission.getDate()));
                ps.setString(10, tfAccountNo.getText());
                ps.setInt(11, Integer.parseInt(tfCurrentClass.getText()));
                ps.setString(12, tfCurrentSection.getText());
                // ps.setInt(12,comboIsCurrentStudent.getSelectedIndex());
                ps.setString(13, dtformat.format(dateDateOfAdmission.getDate()));
                ps.setString(14, tfUsername.getText());
                ps.setString(15, tfPassword.getText());
                ps.setInt(16, comboIsCurrentStudent.getSelectedIndex());

                ps.executeUpdate();

                System.out.println("updated successfully");

                JOptionPane.showMessageDialog(frameSignUpAsStudentbyADMIN.this, tfFirstname.getText() + " added successfully");

                tfFirstname.setText(null);
                tfLastname.setText(null);
                tfFathersname.setText(null);
                tfMothersName.setText(null);
                dateBirthday.setDate(null);
                tfBlood.setText(null);
                tfPhone.setText(null);
                tfEmail.setText(null);
                tfAddress.setText(null);
                tfAccountNo.setText(null);
                tfCurrentClass.setText(null);
                dateDateOfAdmission.setDate(null);
                tfUsername.setText(null);
                tfPassword.setText(null);
                comboIsCurrentStudent.setSelectedIndex(1);
                /* Statement statement = connection.createStatement();
            ResultSet resultSet = statement
            .executeQuery("SELECT * FROM StudentTable");
            while (resultSet.next()) {
                System.out.println(resultSet.getString("studentFirstName") + " " + resultSet.getString("studentLastName"));
            }*/
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        //JOptionPane.showMessageDialog(frameSignUpAsStudentbyADMIN.this,tfStudentId_signStdbyADM.getText()+ " added successfully");

    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frameADMINHomePage aDMINHomePage = new frameADMINHomePage();
        aDMINHomePage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLastnameActionPerformed

    private void tfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneActionPerformed

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameSignUpAsStudentbyADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameSignUpAsStudentbyADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameSignUpAsStudentbyADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameSignUpAsStudentbyADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameSignUpAsStudentbyADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> comboIsCurrentStudent;
    private com.toedter.calendar.JDateChooser dateBirthday;
    private com.toedter.calendar.JDateChooser dateDateOfAdmission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField tfAccountNo;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfBlood;
    private javax.swing.JTextField tfCurrentClass;
    private javax.swing.JTextField tfCurrentSection;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFathersname;
    private javax.swing.JTextField tfFirstname;
    private javax.swing.JTextField tfLastname;
    private javax.swing.JTextField tfMothersName;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
